// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Odyseusz.dal;

#nullable disable

namespace Odyseusz.dal.Migrations
{
    [DbContext(typeof(OdyseuszDbContext))]
    [Migration("20241202171950_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Odyseusz.domain.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Miejscowosc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaKraju")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NrDomu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NrLokalu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NazwaKraju");

                    b.ToTable("Adresy");
                });

            modelBuilder.Entity("Odyseusz.domain.DaneOsobowe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdresId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NrTelefonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdresId");

                    b.ToTable("DaneOsobowe");
                });

            modelBuilder.Entity("Odyseusz.domain.EtapPodrozy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdresId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DataPrzyjazdu")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataWyjazdu")
                        .HasColumnType("date");

                    b.Property<int>("OrganizatorPobytu")
                        .HasColumnType("int");

                    b.Property<int?>("ZgloszeniePodrozyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdresId");

                    b.HasIndex("ZgloszeniePodrozyId");

                    b.ToTable("EtapyPodrozy");
                });

            modelBuilder.Entity("Odyseusz.domain.Kraj", b =>
                {
                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KodKraju")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nazwa");

                    b.ToTable("Kraje");

                    b.HasData(
                        new
                        {
                            Nazwa = "Afganistan",
                            KodKraju = "AF"
                        },
                        new
                        {
                            Nazwa = "Albania",
                            KodKraju = "AL"
                        },
                        new
                        {
                            Nazwa = "Algieria",
                            KodKraju = "DZ"
                        },
                        new
                        {
                            Nazwa = "Andora",
                            KodKraju = "AD"
                        },
                        new
                        {
                            Nazwa = "Angola",
                            KodKraju = "AO"
                        },
                        new
                        {
                            Nazwa = "Antigua i Barbuda",
                            KodKraju = "AG"
                        },
                        new
                        {
                            Nazwa = "Arabia Saudyjska",
                            KodKraju = "SA"
                        },
                        new
                        {
                            Nazwa = "Argentyna",
                            KodKraju = "AR"
                        },
                        new
                        {
                            Nazwa = "Armenia",
                            KodKraju = "AM"
                        },
                        new
                        {
                            Nazwa = "Australia",
                            KodKraju = "AU"
                        },
                        new
                        {
                            Nazwa = "Austria",
                            KodKraju = "AT"
                        },
                        new
                        {
                            Nazwa = "Azerbejdżan",
                            KodKraju = "AZ"
                        },
                        new
                        {
                            Nazwa = "Bahamy",
                            KodKraju = "BS"
                        },
                        new
                        {
                            Nazwa = "Bahrajn",
                            KodKraju = "BH"
                        },
                        new
                        {
                            Nazwa = "Bangladesz",
                            KodKraju = "BD"
                        },
                        new
                        {
                            Nazwa = "Barbados",
                            KodKraju = "BB"
                        },
                        new
                        {
                            Nazwa = "Belgia",
                            KodKraju = "BE"
                        },
                        new
                        {
                            Nazwa = "Belize",
                            KodKraju = "BZ"
                        },
                        new
                        {
                            Nazwa = "Benin",
                            KodKraju = "BJ"
                        },
                        new
                        {
                            Nazwa = "Bhutan",
                            KodKraju = "BT"
                        },
                        new
                        {
                            Nazwa = "Białoruś",
                            KodKraju = "BY"
                        },
                        new
                        {
                            Nazwa = "Bośnia i Hercegowina",
                            KodKraju = "BA"
                        },
                        new
                        {
                            Nazwa = "Botswana",
                            KodKraju = "BW"
                        },
                        new
                        {
                            Nazwa = "Brazylia",
                            KodKraju = "BR"
                        },
                        new
                        {
                            Nazwa = "Brunei",
                            KodKraju = "BN"
                        },
                        new
                        {
                            Nazwa = "Bułgaria",
                            KodKraju = "BG"
                        },
                        new
                        {
                            Nazwa = "Burkina Faso",
                            KodKraju = "BF"
                        },
                        new
                        {
                            Nazwa = "Burundi",
                            KodKraju = "BI"
                        },
                        new
                        {
                            Nazwa = "Chile",
                            KodKraju = "CL"
                        },
                        new
                        {
                            Nazwa = "Chiny",
                            KodKraju = "CN"
                        },
                        new
                        {
                            Nazwa = "Chorwacja",
                            KodKraju = "HR"
                        },
                        new
                        {
                            Nazwa = "Cypr",
                            KodKraju = "CY"
                        },
                        new
                        {
                            Nazwa = "Czarnogóra",
                            KodKraju = "ME"
                        },
                        new
                        {
                            Nazwa = "Czechy",
                            KodKraju = "CZ"
                        },
                        new
                        {
                            Nazwa = "Dania",
                            KodKraju = "DK"
                        },
                        new
                        {
                            Nazwa = "Demokratyczna Republika Konga",
                            KodKraju = "CD"
                        },
                        new
                        {
                            Nazwa = "Dominika",
                            KodKraju = "DM"
                        },
                        new
                        {
                            Nazwa = "Dominikana",
                            KodKraju = "DO"
                        },
                        new
                        {
                            Nazwa = "Dżibuti",
                            KodKraju = "DJ"
                        },
                        new
                        {
                            Nazwa = "Egipt",
                            KodKraju = "EG"
                        },
                        new
                        {
                            Nazwa = "Ekwador",
                            KodKraju = "EC"
                        },
                        new
                        {
                            Nazwa = "Erytrea",
                            KodKraju = "ER"
                        },
                        new
                        {
                            Nazwa = "Estonia",
                            KodKraju = "EE"
                        },
                        new
                        {
                            Nazwa = "Eswatini",
                            KodKraju = "SZ"
                        },
                        new
                        {
                            Nazwa = "Etiopia",
                            KodKraju = "ET"
                        },
                        new
                        {
                            Nazwa = "Fidżi",
                            KodKraju = "FJ"
                        },
                        new
                        {
                            Nazwa = "Filipiny",
                            KodKraju = "PH"
                        },
                        new
                        {
                            Nazwa = "Finlandia",
                            KodKraju = "FI"
                        },
                        new
                        {
                            Nazwa = "Francja",
                            KodKraju = "FR"
                        },
                        new
                        {
                            Nazwa = "Gabon",
                            KodKraju = "GA"
                        },
                        new
                        {
                            Nazwa = "Gambia",
                            KodKraju = "GM"
                        },
                        new
                        {
                            Nazwa = "Ghana",
                            KodKraju = "GH"
                        },
                        new
                        {
                            Nazwa = "Grecja",
                            KodKraju = "GR"
                        },
                        new
                        {
                            Nazwa = "Grenada",
                            KodKraju = "GD"
                        },
                        new
                        {
                            Nazwa = "Gruzja",
                            KodKraju = "GE"
                        },
                        new
                        {
                            Nazwa = "Guatemala",
                            KodKraju = "GT"
                        },
                        new
                        {
                            Nazwa = "Gwinea",
                            KodKraju = "GN"
                        },
                        new
                        {
                            Nazwa = "Gwinea Bissau",
                            KodKraju = "GW"
                        },
                        new
                        {
                            Nazwa = "Gwinea Równikowa",
                            KodKraju = "GQ"
                        },
                        new
                        {
                            Nazwa = "Gujana",
                            KodKraju = "GY"
                        },
                        new
                        {
                            Nazwa = "Haiti",
                            KodKraju = "HT"
                        },
                        new
                        {
                            Nazwa = "Hiszpania",
                            KodKraju = "ES"
                        },
                        new
                        {
                            Nazwa = "Holandia",
                            KodKraju = "NL"
                        },
                        new
                        {
                            Nazwa = "Honduras",
                            KodKraju = "HN"
                        },
                        new
                        {
                            Nazwa = "Indie",
                            KodKraju = "IN"
                        },
                        new
                        {
                            Nazwa = "Indonezja",
                            KodKraju = "ID"
                        },
                        new
                        {
                            Nazwa = "Irak",
                            KodKraju = "IQ"
                        },
                        new
                        {
                            Nazwa = "Iran",
                            KodKraju = "IR"
                        },
                        new
                        {
                            Nazwa = "Irlandia",
                            KodKraju = "IE"
                        },
                        new
                        {
                            Nazwa = "Islandia",
                            KodKraju = "IS"
                        },
                        new
                        {
                            Nazwa = "Izrael",
                            KodKraju = "IL"
                        },
                        new
                        {
                            Nazwa = "Jamajka",
                            KodKraju = "JM"
                        },
                        new
                        {
                            Nazwa = "Japonia",
                            KodKraju = "JP"
                        },
                        new
                        {
                            Nazwa = "Jemen",
                            KodKraju = "YE"
                        },
                        new
                        {
                            Nazwa = "Jordania",
                            KodKraju = "JO"
                        },
                        new
                        {
                            Nazwa = "Kambodża",
                            KodKraju = "KH"
                        },
                        new
                        {
                            Nazwa = "Kamerun",
                            KodKraju = "CM"
                        },
                        new
                        {
                            Nazwa = "Kanada",
                            KodKraju = "CA"
                        },
                        new
                        {
                            Nazwa = "Katar",
                            KodKraju = "QA"
                        },
                        new
                        {
                            Nazwa = "Kazachstan",
                            KodKraju = "KZ"
                        },
                        new
                        {
                            Nazwa = "Kenia",
                            KodKraju = "KE"
                        },
                        new
                        {
                            Nazwa = "Kirgistan",
                            KodKraju = "KG"
                        },
                        new
                        {
                            Nazwa = "Kiribati",
                            KodKraju = "KI"
                        },
                        new
                        {
                            Nazwa = "Kolumbia",
                            KodKraju = "CO"
                        },
                        new
                        {
                            Nazwa = "Komory",
                            KodKraju = "KM"
                        },
                        new
                        {
                            Nazwa = "Kongo",
                            KodKraju = "CG"
                        },
                        new
                        {
                            Nazwa = "Korea Południowa",
                            KodKraju = "KR"
                        },
                        new
                        {
                            Nazwa = "Korea Północna",
                            KodKraju = "KP"
                        },
                        new
                        {
                            Nazwa = "Kostaryka",
                            KodKraju = "CR"
                        },
                        new
                        {
                            Nazwa = "Kuba",
                            KodKraju = "CU"
                        },
                        new
                        {
                            Nazwa = "Kuwejt",
                            KodKraju = "KW"
                        },
                        new
                        {
                            Nazwa = "Laos",
                            KodKraju = "LA"
                        },
                        new
                        {
                            Nazwa = "Lesotho",
                            KodKraju = "LS"
                        },
                        new
                        {
                            Nazwa = "Liban",
                            KodKraju = "LB"
                        },
                        new
                        {
                            Nazwa = "Liberia",
                            KodKraju = "LR"
                        },
                        new
                        {
                            Nazwa = "Libia",
                            KodKraju = "LY"
                        },
                        new
                        {
                            Nazwa = "Liechtenstein",
                            KodKraju = "LI"
                        },
                        new
                        {
                            Nazwa = "Litwa",
                            KodKraju = "LT"
                        },
                        new
                        {
                            Nazwa = "Luksemburg",
                            KodKraju = "LU"
                        },
                        new
                        {
                            Nazwa = "Łotwa",
                            KodKraju = "LV"
                        },
                        new
                        {
                            Nazwa = "Madagaskar",
                            KodKraju = "MG"
                        },
                        new
                        {
                            Nazwa = "Malawi",
                            KodKraju = "MW"
                        },
                        new
                        {
                            Nazwa = "Malediwy",
                            KodKraju = "MV"
                        },
                        new
                        {
                            Nazwa = "Malezja",
                            KodKraju = "MY"
                        },
                        new
                        {
                            Nazwa = "Mali",
                            KodKraju = "ML"
                        },
                        new
                        {
                            Nazwa = "Malta",
                            KodKraju = "MT"
                        },
                        new
                        {
                            Nazwa = "Maroko",
                            KodKraju = "MA"
                        },
                        new
                        {
                            Nazwa = "Mauritius",
                            KodKraju = "MU"
                        },
                        new
                        {
                            Nazwa = "Mauritania",
                            KodKraju = "MR"
                        },
                        new
                        {
                            Nazwa = "Meksyk",
                            KodKraju = "MX"
                        },
                        new
                        {
                            Nazwa = "Micronezja",
                            KodKraju = "FM"
                        },
                        new
                        {
                            Nazwa = "Mołdawia",
                            KodKraju = "MD"
                        },
                        new
                        {
                            Nazwa = "Monako",
                            KodKraju = "MC"
                        },
                        new
                        {
                            Nazwa = "Mongolia",
                            KodKraju = "MN"
                        },
                        new
                        {
                            Nazwa = "Mozambik",
                            KodKraju = "MZ"
                        },
                        new
                        {
                            Nazwa = "Myanmar",
                            KodKraju = "MM"
                        },
                        new
                        {
                            Nazwa = "Namibia",
                            KodKraju = "NA"
                        },
                        new
                        {
                            Nazwa = "Nauru",
                            KodKraju = "NR"
                        },
                        new
                        {
                            Nazwa = "Nepal",
                            KodKraju = "NP"
                        },
                        new
                        {
                            Nazwa = "Niemcy",
                            KodKraju = "DE"
                        },
                        new
                        {
                            Nazwa = "Niger",
                            KodKraju = "NE"
                        },
                        new
                        {
                            Nazwa = "Nigeria",
                            KodKraju = "NG"
                        },
                        new
                        {
                            Nazwa = "Nikaragua",
                            KodKraju = "NI"
                        },
                        new
                        {
                            Nazwa = "Norwegia",
                            KodKraju = "NO"
                        },
                        new
                        {
                            Nazwa = "Nowa Zelandia",
                            KodKraju = "NZ"
                        },
                        new
                        {
                            Nazwa = "Oman",
                            KodKraju = "OM"
                        },
                        new
                        {
                            Nazwa = "Pakistan",
                            KodKraju = "PK"
                        },
                        new
                        {
                            Nazwa = "Palau",
                            KodKraju = "PW"
                        },
                        new
                        {
                            Nazwa = "Palestyna",
                            KodKraju = "PS"
                        },
                        new
                        {
                            Nazwa = "Panama",
                            KodKraju = "PA"
                        },
                        new
                        {
                            Nazwa = "Papua-Nowa Gwinea",
                            KodKraju = "PG"
                        },
                        new
                        {
                            Nazwa = "Paragwaj",
                            KodKraju = "PY"
                        },
                        new
                        {
                            Nazwa = "Peru",
                            KodKraju = "PE"
                        },
                        new
                        {
                            Nazwa = "Polska",
                            KodKraju = "PL"
                        },
                        new
                        {
                            Nazwa = "Portugalia",
                            KodKraju = "PT"
                        },
                        new
                        {
                            Nazwa = "Republika Południowej Afryki",
                            KodKraju = "ZA"
                        },
                        new
                        {
                            Nazwa = "Republika Środkowoafrykańska",
                            KodKraju = "CF"
                        },
                        new
                        {
                            Nazwa = "Republika Zielonego Przylądka",
                            KodKraju = "CV"
                        },
                        new
                        {
                            Nazwa = "Rosja",
                            KodKraju = "RU"
                        },
                        new
                        {
                            Nazwa = "Rumunia",
                            KodKraju = "RO"
                        },
                        new
                        {
                            Nazwa = "Rwanda",
                            KodKraju = "RW"
                        },
                        new
                        {
                            Nazwa = "Saint Kitts i Nevis",
                            KodKraju = "KN"
                        },
                        new
                        {
                            Nazwa = "Saint Lucia",
                            KodKraju = "LC"
                        },
                        new
                        {
                            Nazwa = "Saint Vincent i Grenadyny",
                            KodKraju = "VC"
                        },
                        new
                        {
                            Nazwa = "Salwador",
                            KodKraju = "SV"
                        },
                        new
                        {
                            Nazwa = "Samoa",
                            KodKraju = "WS"
                        },
                        new
                        {
                            Nazwa = "San Marino",
                            KodKraju = "SM"
                        },
                        new
                        {
                            Nazwa = "Senegal",
                            KodKraju = "SN"
                        },
                        new
                        {
                            Nazwa = "Serbia",
                            KodKraju = "RS"
                        },
                        new
                        {
                            Nazwa = "Seychele",
                            KodKraju = "SC"
                        },
                        new
                        {
                            Nazwa = "Sierra Leone",
                            KodKraju = "SL"
                        },
                        new
                        {
                            Nazwa = "Singapur",
                            KodKraju = "SG"
                        },
                        new
                        {
                            Nazwa = "Słowacja",
                            KodKraju = "SK"
                        },
                        new
                        {
                            Nazwa = "Słowenia",
                            KodKraju = "SI"
                        },
                        new
                        {
                            Nazwa = "Somalia",
                            KodKraju = "SO"
                        },
                        new
                        {
                            Nazwa = "Sri Lanka",
                            KodKraju = "LK"
                        },
                        new
                        {
                            Nazwa = "Stany Zjednoczone",
                            KodKraju = "US"
                        },
                        new
                        {
                            Nazwa = "Sudan",
                            KodKraju = "SD"
                        },
                        new
                        {
                            Nazwa = "Surinam",
                            KodKraju = "SR"
                        },
                        new
                        {
                            Nazwa = "Syria",
                            KodKraju = "SY"
                        },
                        new
                        {
                            Nazwa = "Szwajcaria",
                            KodKraju = "CH"
                        },
                        new
                        {
                            Nazwa = "Szwecja",
                            KodKraju = "SE"
                        },
                        new
                        {
                            Nazwa = "Tadżykistan",
                            KodKraju = "TJ"
                        },
                        new
                        {
                            Nazwa = "Tajlandia",
                            KodKraju = "TH"
                        },
                        new
                        {
                            Nazwa = "Tanzania",
                            KodKraju = "TZ"
                        },
                        new
                        {
                            Nazwa = "Timor Wschodni",
                            KodKraju = "TL"
                        },
                        new
                        {
                            Nazwa = "Togo",
                            KodKraju = "TG"
                        },
                        new
                        {
                            Nazwa = "Tokelau",
                            KodKraju = "TK"
                        },
                        new
                        {
                            Nazwa = "Trynidad i Tobago",
                            KodKraju = "TT"
                        },
                        new
                        {
                            Nazwa = "Tunisia",
                            KodKraju = "TN"
                        },
                        new
                        {
                            Nazwa = "Turkmenistan",
                            KodKraju = "TM"
                        },
                        new
                        {
                            Nazwa = "Turcja",
                            KodKraju = "TR"
                        },
                        new
                        {
                            Nazwa = "Tuvalu",
                            KodKraju = "TV"
                        },
                        new
                        {
                            Nazwa = "Uganda",
                            KodKraju = "UG"
                        },
                        new
                        {
                            Nazwa = "Urugwaj",
                            KodKraju = "UY"
                        },
                        new
                        {
                            Nazwa = "Uzbekistan",
                            KodKraju = "UZ"
                        },
                        new
                        {
                            Nazwa = "Vanuatu",
                            KodKraju = "VU"
                        },
                        new
                        {
                            Nazwa = "Venezuela",
                            KodKraju = "VE"
                        },
                        new
                        {
                            Nazwa = "Watykan",
                            KodKraju = "VA"
                        },
                        new
                        {
                            Nazwa = "Wielka Brytania",
                            KodKraju = "GB"
                        },
                        new
                        {
                            Nazwa = "Wietnam",
                            KodKraju = "VN"
                        },
                        new
                        {
                            Nazwa = "Węgry",
                            KodKraju = "HU"
                        },
                        new
                        {
                            Nazwa = "Włochy",
                            KodKraju = "IT"
                        },
                        new
                        {
                            Nazwa = "Zambia",
                            KodKraju = "ZM"
                        },
                        new
                        {
                            Nazwa = "Zimbabwe",
                            KodKraju = "ZW"
                        });
                });

            modelBuilder.Entity("Odyseusz.domain.ZgloszeniePodrozy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DaneOsoboweId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataZgloszenia")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DaneOsoboweId");

                    b.ToTable("ZgloszeniaPodrozy");
                });

            modelBuilder.Entity("Odyseusz.domain.Adres", b =>
                {
                    b.HasOne("Odyseusz.domain.Kraj", "Kraj")
                        .WithMany()
                        .HasForeignKey("NazwaKraju")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kraj");
                });

            modelBuilder.Entity("Odyseusz.domain.DaneOsobowe", b =>
                {
                    b.HasOne("Odyseusz.domain.Adres", "Adres")
                        .WithMany()
                        .HasForeignKey("AdresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adres");
                });

            modelBuilder.Entity("Odyseusz.domain.EtapPodrozy", b =>
                {
                    b.HasOne("Odyseusz.domain.Adres", "Adres")
                        .WithMany()
                        .HasForeignKey("AdresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Odyseusz.domain.ZgloszeniePodrozy", null)
                        .WithMany("EtapyPodrozy")
                        .HasForeignKey("ZgloszeniePodrozyId");

                    b.Navigation("Adres");
                });

            modelBuilder.Entity("Odyseusz.domain.ZgloszeniePodrozy", b =>
                {
                    b.HasOne("Odyseusz.domain.DaneOsobowe", "DaneOsobowe")
                        .WithMany()
                        .HasForeignKey("DaneOsoboweId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaneOsobowe");
                });

            modelBuilder.Entity("Odyseusz.domain.ZgloszeniePodrozy", b =>
                {
                    b.Navigation("EtapyPodrozy");
                });
#pragma warning restore 612, 618
        }
    }
}
